"""Local setup helpers; no model calls."""
from __future__ import annotations

import json
import shlex
import shutil
import subprocess
import sys
from pathlib import Path


CONFIG_NAME = '.rulebisect.json'


def git_root(path: Path) -> Path:
    result = subprocess.run(['git', '-c', 'core.fsmonitor=false', 'rev-parse', '--show-toplevel'],
                            cwd=path, capture_output=True, text=True, timeout=10)
    if result.returncode:
        raise ValueError('Not inside a Git repository. Run git init and git add for the fixture first.')
    return Path(result.stdout.strip()).resolve()


def tracked_files(repo: Path) -> list[str]:
    result = subprocess.run(['git', '-c', 'core.fsmonitor=false', 'ls-files', '-z'], cwd=repo,
                            capture_output=True, timeout=10, check=True)
    return [name for name in result.stdout.decode().split('\0') if name]


def discover_instructions(repo: Path) -> list[str]:
    names = set(tracked_files(repo))
    names.update(name for name in ['AGENTS.md', 'AGENTS.override.md'] if (repo / name).is_file())
    candidates = {name for name in names if Path(name).name in ('AGENTS.md', 'AGENTS.override.md')
                  and (repo / name).is_file() and not (repo / name).is_symlink()}
    return sorted(name for name in candidates if Path(name).name == 'AGENTS.override.md'
                  or str(Path(name).with_name('AGENTS.override.md')) not in candidates)


def init_config(repo: Path, task: str, check: str | None, model: str | None,
                oracle: str | None = None, instructions: list[str] | None = None) -> Path:
    repo = repo.resolve()
    path = repo / CONFIG_NAME
    if path.exists():
        raise ValueError(f'{CONFIG_NAME} already exists; edit it rather than overwriting.')
    if not task.strip():
        raise ValueError('Provide a concrete --task.')
    selected = instructions or discover_instructions(repo)
    if not selected:
        raise ValueError('No AGENTS.md found. Use --instructions to select an existing instruction/Skill file.')
    for name in selected:
        relative = Path(name)
        target = repo / relative
        if relative.is_absolute() or '..' in relative.parts or not target.is_file() or target.is_symlink() or not target.resolve().is_relative_to(repo):
            raise ValueError(f'Instruction file is missing or outside the repository: {name}')
    names = tracked_files(repo)
    protected = [name for name in names if (Path(name).name.startswith(('test_', 'test.'))
                  or Path(name).name.endswith(('_test.py', '.test.ts', '.test.js', '.spec.ts', '.spec.js')))
                 and name not in selected and (repo / name).is_file()]
    if oracle is None:
        if not check:
            raise ValueError('Choose --check "your test command" or --oracle existing-verifier.py.')
        argv = shlex.split(check)
        if not argv:
            raise ValueError('--check must be a command, not empty text.')
        if any(value in ('&&', '||', ';', '|', '>', '>>', '<') for value in argv):
            raise ValueError('Shell operators are unsupported. Use --oracle for multiple checks.')
        oracle = '.rulebisect-verify.py'
        oracle_path = repo / oracle
        if oracle_path.exists():
            raise ValueError(f'{oracle} already exists; use --oracle or rename it.')
        source = '''# Generated by RuleBisect. Runs your trusted check without a shell.
import subprocess
import sys
COMMAND = CHECK_ARGUMENTS
if COMMAND[0] in ('python', 'python3'):
    COMMAND[0] = sys.executable
try:
    result = subprocess.run(COMMAND)
except OSError as error:
    print('Verifier setup error:', error, file=sys.stderr)
    sys.exit(2)
# Exit 1 is a behavioral failure; other codes are infrastructure errors.
sys.exit(result.returncode if result.returncode in (0, 1) else 2)
'''.replace('CHECK_ARGUMENTS', repr(argv))
        oracle_path.write_text(source, encoding='utf-8')
    else:
        rel = Path(oracle)
        target = repo / rel
        if rel.is_absolute() or '..' in rel.parts or not target.is_file() or target.is_symlink() or not target.resolve().is_relative_to(repo):
            raise ValueError('--oracle must name an existing repository-relative verifier.')
    if oracle in selected:
        raise ValueError('The oracle cannot also be an instruction file.')
    config = {'task': task, 'instructions': selected, 'oracle': oracle,
              'verify': ['{python}', '{oracle}'], 'protected_files': sorted(set(protected + [oracle])),
              'repeats': 3, 'max_runs': 60, 'timeout': 300, 'unit_mode': 'paragraph'}
    if model:
        config['model'] = model
    path.write_text(json.dumps(config, ensure_ascii=False, indent=2) + '\n', encoding='utf-8')
    return path


def doctor(repo: Path) -> dict:
    checks = []
    def add(name, ok, detail):
        checks.append({'name': name, 'ok': ok, 'detail': detail})
    add('Python', sys.version_info >= (3, 11), sys.version.split()[0])
    add('Git executable', shutil.which('git') is not None, shutil.which('git') or 'Install Git')
    try:
        root = git_root(repo)
        add('Git repository', True, str(root))
        files = discover_instructions(root)
        config = root / CONFIG_NAME
        if config.is_file():
            try:
                configured = json.loads(config.read_text(encoding='utf-8'))
                selected = configured.get('instructions', []) if isinstance(configured, dict) else []
                if isinstance(selected, list) and selected:
                    files = [name for name in selected if isinstance(name, str) and not Path(name).is_absolute()
                             and '..' not in Path(name).parts and (root / name).is_file()
                             and not (root / name).is_symlink() and (root / name).resolve().is_relative_to(root)]
                    add('Configured instructions', len(files) == len(selected), ', '.join(files) or 'Configured files missing')
                else:
                    add('Configured instructions', False, 'Config needs a non-empty instructions list')
            except (ValueError, OSError) as error:
                add('Config syntax', False, str(error))
        else:
            add('Instruction files', bool(files), ', '.join(files) or 'None found; select files with init --instructions')
        add('Experiment config', config.is_file(), str(config) if config.is_file() else 'Run rulebisect init')
    except (ValueError, OSError, subprocess.SubprocessError) as error:
        add('Git repository', False, str(error))
    if not shutil.which('codex'):
        add('Codex executable', False, 'Install the Codex CLI')
    else:
        try:
            version = subprocess.run(['codex', '--version'], capture_output=True, text=True, timeout=10, check=True)
            add('Codex version', True, version.stdout.strip())
            help_text = subprocess.run(['codex', 'exec', '--help'], capture_output=True, text=True, timeout=10, check=True).stdout
            missing = [flag for flag in ['--json', '--ephemeral', '--ignore-user-config'] if flag not in help_text]
            add('Codex flags', not missing, 'Supported' if not missing else 'Update Codex; missing ' + ', '.join(missing))
            auth = subprocess.run(['codex', 'login', 'status'], capture_output=True, timeout=10)
            # Do not print authentication output, which may include an API-key hint.
            add('Codex authentication', auth.returncode == 0, 'Logged in' if auth.returncode == 0 else 'Run codex login')
        except (OSError, subprocess.SubprocessError) as error:
            add('Codex check', False, str(error))
    return {'ok': all(c['ok'] for c in checks), 'checks': checks, 'model_calls': 0}
