"""Manage regression cases locally, without running checks or calling a model."""
from __future__ import annotations

import copy
import json
import os
import shlex
import tempfile
from pathlib import Path

from .comparison import suite_cases


def _safe_config_path(path: Path) -> Path:
    # Resolve directory aliases (for example macOS /tmp -> /private/tmp),
    # but do not silently replace a config entry that itself is a symlink.
    path = Path(path)
    path = path.parent.resolve() / path.name
    if path.is_symlink():
        raise ValueError('Config files must not be symlinks')
    if not path.is_file():
        raise ValueError(f'Config file does not exist: {path}. Run rulebisect init first.')
    return path


def _load_config(config_path: Path) -> tuple[Path, dict, bytes]:
    path = _safe_config_path(config_path)
    original = path.read_bytes()
    config = json.loads(original.decode('utf-8'))
    if not isinstance(config, dict):
        raise ValueError('Config must be a JSON object')
    suite_cases(config)
    return path, config, original


def _write_config(path: Path, config: dict, original: bytes) -> None:
    """Replace JSON atomically, refusing to overwrite an intervening user edit."""
    _safe_config_path(path)
    mode = path.stat().st_mode & 0o777
    temporary = None
    try:
        with tempfile.NamedTemporaryFile(mode='w', encoding='utf-8', newline='\n',
                                         dir=path.parent, prefix=path.name + '.',
                                         suffix='.tmp', delete=False) as stream:
            temporary = Path(stream.name)
            stream.write(json.dumps(config, ensure_ascii=False, indent=2) + '\n')
            stream.flush()
            os.fsync(stream.fileno())
        temporary.chmod(mode)
        _safe_config_path(path)
        if path.read_bytes() != original:
            raise ValueError('Config changed while editing the suite; retry with the updated file')
        os.replace(temporary, path)
    finally:
        if temporary is not None and temporary.exists():
            temporary.unlink()


def _relative_file(repo: Path, name: str, *, must_exist: bool) -> str:
    if not isinstance(name, str) or not name:
        raise ValueError('File paths must be non-empty repository-relative strings')
    relative = Path(name)
    if relative.is_absolute() or '..' in relative.parts or '.git' in relative.parts:
        raise ValueError(f'Expected a repository-relative file path: {name}')
    target = repo / relative
    if any((repo / Path(*relative.parts[:index])).is_symlink()
           for index in range(1, len(relative.parts) + 1)):
        raise ValueError(f'File paths and their parent directories must not be symlinks: {name}')
    if not target.resolve().is_relative_to(repo):
        raise ValueError(f'File is outside the repository: {name}')
    if must_exist and not target.is_file():
        raise ValueError(f'File does not exist: {name}')
    if not must_exist:
        existing_name = (target.exists() or (target.parent.is_dir() and
                         any(child.name.casefold() == target.name.casefold()
                             for child in target.parent.iterdir())))
        if existing_name:
            raise ValueError(f'Generated verifier already exists: {name}; use --oracle or choose another id')
    for parent in target.parents:
        if parent == repo:
            break
        if parent.exists() and not parent.is_dir():
            raise ValueError(f'Expected a directory for the verifier: {parent.relative_to(repo)}')
    return relative.as_posix()


def _command_source(check: str) -> str:
    if not isinstance(check, str):
        raise ValueError('--check must be a command string')
    arguments = shlex.split(check)
    if not arguments or any('\0' in value for value in arguments):
        raise ValueError('--check must contain a valid command')
    if any(value in ('&&', '||', ';', '|', '>', '>>', '<') for value in arguments):
        raise ValueError('Shell operators are unsupported. Use --oracle for multiple checks.')
    return '''# Generated by RuleBisect. Runs your trusted check without a shell.
import subprocess
import sys

COMMAND = CHECK_ARGUMENTS
if COMMAND[0] in ('python', 'python3', '{python}'):
    COMMAND[0] = sys.executable
try:
    result = subprocess.run(COMMAND)
except OSError as error:
    print('Verifier setup error:', error, file=sys.stderr)
    sys.exit(2)
# Exit 1 is a behavioral failure; other codes are infrastructure errors.
sys.exit(result.returncode if result.returncode in (0, 1) else 2)
'''.replace('CHECK_ARGUMENTS', repr(arguments))


def list_cases(config_path: Path) -> list[dict]:
    """Return effective ``id/task/oracle/verify/protected_files`` for every case.

    An existing configuration without ``cases`` is represented by the implicit
    ``task`` case. Missing effective fields are ``None`` (protected files: []).
    This reads configuration only; it does not execute or inspect check commands.
    """
    _, config, _ = _load_config(config_path)
    return [{'id': name, 'task': case.get('task'), 'oracle': case.get('oracle'),
             'verify': copy.deepcopy(case.get('verify')),
             'protected_files': copy.deepcopy(case.get('protected_files', []))}
            for name, case in suite_cases(config)]


def add_case(repo: Path, config_path: Path, case_id: str, task: str,
             check: str | None = None, oracle: str | None = None) -> dict:
    """Append a case and return its fields plus creation/configuration metadata.

    The result contains ``id/task/oracle/verify/generated_oracle/case_count/config``.
    Exactly one of ``check`` and ``oracle`` is required. A check creates a new
    ``.rulebisect/checks/<id>.py`` wrapper; neither check commands nor models run.
    The old implicit ``task`` case survives conversion to an explicit suite.
    """
    repo = Path(repo).resolve()
    if not repo.is_dir():
        raise ValueError('Repository directory does not exist')
    path, config, original = _load_config(config_path)
    if not isinstance(task, str) or not task.strip():
        raise ValueError('Provide a concrete --task for the case')
    if (check is None) == (oracle is None):
        raise ValueError('Choose exactly one of --check or --oracle')
    updated = copy.deepcopy(config)
    cases = updated.setdefault('cases', [{'id': 'task'}])
    case = {'id': case_id, 'task': task, 'oracle': oracle,
            'verify': ['{python}', '{oracle}']}
    cases.append(case)
    # Validate ids/schema before interpolating the id into any filesystem path.
    suite_cases(updated)
    source = _command_source(check) if check is not None else None
    selected = config.get('instructions')
    if not isinstance(selected, list) or not selected:
        raise ValueError('Config requires an explicit instructions list')
    instructions = {_relative_file(repo, name, must_exist=True) for name in selected}
    verifier = _relative_file(repo, f'.rulebisect/checks/{case_id}.py' if source is not None else oracle,
                              must_exist=source is None)
    if verifier in instructions:
        raise ValueError('The oracle cannot also be an instruction file')
    case['oracle'] = verifier
    created = None
    try:
        if source is not None:
            target = repo / verifier
            target.parent.mkdir(parents=True, exist_ok=True)
            # Recheck existing parents after mkdir and use exclusive creation.
            _relative_file(repo, verifier, must_exist=False)
            with target.open('x', encoding='utf-8', newline='\n') as stream:
                created = target
                stream.write(source)
        _write_config(path, updated, original)
    except BaseException:
        if created is not None:
            created.unlink(missing_ok=True)
        raise
    return {**case, 'generated_oracle': created is not None,
            'case_count': len(cases), 'config': str(path)}


def remove_case(config_path: Path, case_id: str) -> dict:
    """Remove a configuration entry, preserving every verifier and user file.

    Return ``id/case_count/config/oracle_preserved``. Removing the final case is
    refused so that an empty suite cannot silently revive the top-level task.
    """
    path, config, original = _load_config(config_path)
    effective = dict(suite_cases(config))
    if case_id not in effective:
        raise ValueError('Unknown case id; choose from: ' + ', '.join(effective))
    if len(effective) == 1:
        raise ValueError('Cannot remove the last case; add its replacement first')
    updated = copy.deepcopy(config)
    updated['cases'] = [case for case in config['cases'] if case['id'] != case_id]
    suite_cases(updated)
    _write_config(path, updated, original)
    return {'id': case_id, 'case_count': len(updated['cases']), 'config': str(path),
            'oracle_preserved': effective[case_id].get('oracle')}
